apiVersion: v1
kind: Service
metadata:
  name:  k8s-web-to-nginx
spec:
  selector:
    app:  k8s-web-to-nginx
  type:  LoadBalancer
  ports:
    - port:  3030
      targetPort:  3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-to-nginx
  labels:
    name: k8s-web-to-nginx
spec:
  selector: 
    matchLabels:
      app: k8s-web-to-nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 3
  template:
    metadata:
      labels:
        app: k8s-web-to-nginx
    spec:
      containers:
      - image:  nielvid/web-nginx
        name: k8s-web-to-nginx
        resources:
          limits:
            cpu: "250m"
            memory: "128Mi"   
        ports:
        - containerPort:  3000
    
        