apiVersion: v1
kind: Service
metadata:
  name:  nginx
spec:
  selector:
    app:  nginx
  ports:
    - port:  80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  selector: 
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image:  nginx
        name: nginx
        resources:
          limits:
            cpu: "250m"
            memory: "128Mi"   
        ports:
        - containerPort:  80
    
        